### PR TITLE
Port teensy-3-assembly for the Teensy LC

### PR DESCRIPTION
**Pull request by SimonSapin**
First of all, many thanks for the well-written and very informative blog posts!

The Teensy I have right now is a [LC](https://www.pjrc.com/teensy/teensyLC.html) which has a different microcontroller, so I’ve had to make a few changes to the code.

There is one set of error messages that I didn’t understand and didn’t manage to fix, so I commented out the corresponding assembly instructions. Is zeroing registers useful anyway?

```
arm-none-eabi-as -g -mcpu=cortex-m0plus -mthumb -o blink.o blink.s
```

``` asm
blink.s: Assembler messages:
blink.s:61: Error: cannot honor width suffix -- `movs r8,#0'
blink.s:62: Error: cannot honor width suffix -- `movs r9,#0'
blink.s:63: Error: cannot honor width suffix -- `movs r10,#0'
blink.s:64: Error: cannot honor width suffix -- `movs r11,#0'
blink.s:65: Error: cannot honor width suffix -- `movs r12,#0'
```

I have a Teensy 3.2 coming in the mail (because the LC is not 5V-tolerant and I want to use a 5 volts I2C device) so I’ll leave porting the C and Rust versions to… whoever feels like it :)

### CODE REVIEW

**Comment by mdaffin** [comment]
Resetting the registers is best practice from what I have read so is not strictly needed if you remember to set them before using them.

r0-r7 are the low registers and r8-12 the high ones. Its seems that not all instructions can access all registers and on the teensy lc the `movs` can only access the first 8 'low' registers. However using

```
    mov     r8,r0
    mov     r9,r0
    mov     r10,r0
    mov     r11,r0
    mov     r12,r0
```

instead allows it to compile for me (though I do not have a teensy lc to test it).

**Comment by SimonSapin** [comment]
That works. I’ve updated the PR. (It’s probably a limitation of Cortex-M0+ vs M4.)

**Comment by mdaffin** [comment]
It might be interesting to see what the c version compiles to for both teensy 3 and lc. If I get some time I might have a look at it.

**Comment by SimonSapin** [comment]
(By the way, did you end up doing something more than blinking a LED with Rust on Teensy?)

**Comment by mdaffin** [comment]
Unfortunately not. I wanted to let the language mature a bit more before getting too deep into using it for embedded work (my rust example has already broken twice since I first wrote it due to upstream changes). In the mean time I have been playing around with stable rust to get more familiar with it.

**Comment by mdaffin** [comment]
I had a quick look at the generated assembly from the c version, it does not use the r8-12 registers at all (not very superising), and only initialises things when it requires them. But then looking at generated code it not the best way to find out how to write idiomatic code, if there are even any strong conventions for assembly.

**Comment by SimonSapin** [comment]
Only initializing things that you use is what I would expect.

**Pull request merged**
